language: csharp
mono: none
services:
  - docker
  
before_install:
  - docker pull ubuntu:latest
  - docker ps -a
  
dotnet: 3.0
script:
  - dotnet build ./app/app.domain/
  - dotnet build ./app/app.persistence/
  - dotnet build ./app/app.web/
