language: csharp
mono: none
services:
  - docker
  
before_install:
  - docker pull ubuntu:latest
  - docker run --name gotham5 ubuntu:latest
  - docker ps -a
  - docker cp ./app gotham5:/
  
dotnet: 3.0
script:
  - dotnet build ./app/app.domain/
  - dotnet build ./app/app.persistence/
  - dotnet build ./app/app.web/
